### ISSUE TITLE
Doubts regarding the project

### ISSUE THREAD

**Issue by Manjuphoenix** [dugalh/simple-ortho#2]
1. Is the code applicable for oblique or slant angle images also or is it only for NADIR images
2. What are the good sources for getting DEM data and EO images along with the associated information required to inference the code for better understanding

Thanks and Regards
Manjunath

**Comment by dugalh** [comment]
Hello Manjunath.  I have only tested the code on [NGI](https://ngi.dalrrd.gov.za/index.php/what-we-do/aerial-photography-and-imagery/35-colour-digital-aerial-imagery-at-0-5m-gsd-2008-2016-and-0-25m-gsd-2017-current) imagery, which is near-nadir.  It should work for oblique images though, so long as it is a pinhole camera, and you have accurate position/orientation info.  

I'm not sure where to get suitable imagery, I can only suggest experimenting with the included [test data](../tree/main/data/inputs/test_example).
